### PR TITLE
Update Marketo User Audit Data Stream Docs for event structure change.

### PR DESCRIPTION
**Pull request by guptapraveen2**
## Description
CET-1021
 - Event structure change, wrapped event details in the body element. 
 - Remove the user field.
 - Add the userId to support easy track of the user details.
## Note
PR raised against which branch -
 - [ ] master (Production)
 - [ ] stage (Stage)

### CODE REVIEW

**Comment by guptapraveen2** [comment]
@bejohnso  Could you please review the event structure changes?

**Comment by rperelma** [comment]
@guptapraveen2 @bejohnso just to let you know this repo will die soon, as we are migrating to https://github.com/AdobeDocs/adobe-io-events, which will go live soon as the replacement. cc: @kgera

**Comment by rperelma** [comment]
@guptapraveen2 @bejohnso just to follow up, make sure you also make the equivalent changes in https://github.com/AdobeDocs/adobe-io-events

**Comment by guptapraveen2** [comment]
> @guptapraveen2 @bejohnso just to follow up, make sure you also make the equivalent changes in https://github.com/AdobeDocs/adobe-io-events

@rperelma Thanks for informing us, I will make equivalent changes in https://github.com/AdobeDocs/adobe-io-events

**Comment by bejohnso** [comment]
@rperelma how soon is the move to the new location happening?

**Review by bejohnso — APPROVED** [review]
@guptapraveen2 changes look good to me

**Comment by rperelma** [comment]
In the next couple weeks. It's all now on @kgera 's shoulders to reach the goal line

**Comment by guptapraveen2** [comment]
Equivalent changes  in other repo https://github.com/AdobeDocs/adobe-io-events/pull/10

**Review by rperelma — APPROVED** [review]
LGTM, you can merge

**Comment by guptapraveen2** [comment]
@rperelma  I don't have write access to merge. Could you please guide me to get that?

**Comment by rperelma** [comment]
No worries, @guptapraveen2 , @kgera will take care of it

**Pull request merged**
