### PR TITLE
[CI-2837]Update AEM events documents

### PR DESCRIPTION
**Pull request by Yu1986**
- Update AEM events documentations clarify it.
- Add AEM 6.5 after verification proxy package work with AEM 6.5 [CI-2837]

### CODE REVIEW

**Comment by Yu1986** [comment]
@francoisledroff

**Comment by francoisledroff** [comment]
👍

**Comment by rperelma** [comment]
@Yu1986   Please work with @MattLusher to merge and figure out why the documentation is not sync'ed with this repo

**Comment by Yu1986** [comment]
@MattLusher Can we merge the doc if it looks good to you ? and I would like to have a short meeting discuss the documentation sync

**Pull request merged**
