### PR TITLE
CI-3295 Experience Platform events (Privacy and Data Ingestion) [CLOSED]

### PR DESCRIPTION
**Pull request by djwendo**
191217_UPDATE: Manifest updated. PR fixes broken link to Privacy Events (formerly GDPR)

NOTE: GDPR Events have been renamed to Privacy Events and the current link on the Adobe I/O Events page is broken.

This PR does the following:
1. Creates a new Experience Platform events doc that links to Data Ingestion and Privacy events documentation within the Experience Platform doc repo
2. Creates a new Privacy events file (in case someone is looking for Privacy events as they are used outside of Experience Platform) and links to the Experience Platform Privacy events doc
3. Updates using.md to include links for both Experience Platform and Privacy event docs

### CODE REVIEW

**Comment by djwendo** [comment]
@kgera I have created this PR to onboard new docs for Experience Platform events. I have included Privacy events as both part of Experience Platform and on its own because it is possible someone will come looking for Privacy events as it is useable/useful outside of Platform.

The Experience Platform events docs (Privacy and Data Ingestion) are live in the Experience Platform documentation area of I/O, so I would like to get the Events repo/doc area updated to match. I have not yet updated the manifest, but can do once this PR is approved.

**Comment by rperelma** [comment]
@djwendo do you want me to approve, or are you expecting @kgera to approve?

**Comment by djwendo** [comment]
@rperelma if you can review that would be great. I have not updated the manifest yet, should I do that in a separate PR into the stage-toc branch?

**Comment by rperelma** [comment]
@djwendo I did review and it looks good. Obviously I am not familiar with the internals of the data platform, but the documentation looks reasonable. Please change the manifest, and then I'll approve the whole package so you can merge. Thanks!

**Comment by djwendo** [comment]
Thanks @rperelma! I have updated the manifest in this PR, so it should be ready to merge.

**Comment by rperelma** [comment]
@djwendo thanks, go ahead and merge it! Or we can ask @macdonst @hirenoble or @kgera to merge it

**Comment by djwendo** [comment]
@rperelma, once merged into staging, what is the staging link to test the documentation? And can I PR staging into master directly to publish the changes on the live site, or is there a specific process for that in this repo (every repo runs a bit differently...) ? cc @macdonst @hirenoble @kgera

**Comment by rperelma** [comment]
As far as I'm concerned, feel free to go straight to master to the live site, @djwendo

**Comment by rperelma** [comment]
@djwendo what is your ETA to merge this to master?

**Comment by djwendo** [comment]
@rperelma if I change the base branch to master I end up pulling in several commits that I didn't make. Should I make a new PR based off master and close this one?

**Comment by rperelma** [comment]
Yes, please, that's a good plan @djwendo

**Comment by djwendo** [comment]
Superseded by PR #35

**Pull request closed without merging**
